### ISSUE TITLE
Error in environment setup

### ISSUE THREAD

**Issue by michaelwilliamtang** [google/belief-localization#2]
```
ERROR: Cannot install transformers 4.15.0 (from git+https://github.com/kmeng01/transformers-colab@allennlp-compat) and transformers==4.21.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested transformers 4.15.0 (from git+https://github.com/kmeng01/transformers-colab@allennlp-compat)
    The user requested transformers==4.21.0
```
We're using Python 3.10.8 and ran the instructions in ReadMe, i.e. `pip install -r requirements.txt` inside `third_party`

**Comment by peterbhase** [comment]
Sorry about that! After setting up a python virtual env with `virtualenv` (instead of conda), you will still get an error from `pip install -r requirements.txt`, but all the code will still run. Of course this isn't a great solution, but try that for now! I'll change the README to reflect this too.
